language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: bgnCZwyLqoO1vfbqtrEh1sac0R9thDMv84McCjuZNuXd+VBLd3dUQuji0qpaCNcTC8HL6f+DcBtUW1LMtdGB6UFFkzUpKWQRqWfXip0ltR7y9uTe5wmsGgPadRwwuTj+63kPfv/ci2Vt6X2dz1OLV5xZecScLZ+X3l5OwpjIvCFGRc5nAOWcvr6rJBwzIwUJKc/frk6ow4alDR6+Ua6ihvELbCoegbdwpc8BkjuQavsoVF+Iu2i5NgsrHqnWzABVDVRCdnqvjuTvrLIfuGDY+NF8UWFB63GS/Bpq2nAjHC5F0ke1V4fZRr+Vl7c65qz2D04N3eYG/XDJSFR4kLmu0eAJYmPMqvaKBlTtywabL8ioOydgNp5JylAo+N/xBhevtKOWv0cC9//fjC+lHaEJRwq9aklsZzh8g2szTQf6/e8LblzyRW3W6rIlpqlcKCmDO8ulu3rEgIL3uVzlYp5ifjPkfFX9+Gg4QcgjtYv9sXcRXngazXBpqepDYCC8C7R7wmN7M1L6+n7dmPBuLwqUXh3bKOQFKUmr6jmNUb6a7L4drYEwexkDB2g+watMiBSLI1S5k5GLq/qnw6lNIWA/DlFJX54nJs7Rq+3SrLKnmu2nQjmg5B3muBGiFUClTVAa0X8DS5e2h8PjCgBBUNOmPNdWrXe4fZ2Y7tZTQL1VKk0=
